#!/bin/bash
#
# Copyright 2020 Red Hat, Inc.
#
# NAME
#     lab-monitor-troubleshoot - lab script for DO380-OCP4
#
# SYNOPSIS
#     lab-monitor-troubleshoot {start|finish}
#
#        start  - prepare the system for starting the lab
#        finish - perform post-lab finish
#
# DESCRIPTION
#     This script, based on singular argument, either does start or finish for
#     the [name of the exercise]
#
# CHANGELOG
#   * Wed Jul 29 Michael Phillips <miphilli@redhat.com>
#   - added the ocp4_login_as_admin function after the ocp4_is_cluster_up function
#   * Tue Jul 14 Michael Phillips <miphilli@redhat.com>
#   - initial creation


PATH=/usr/bin:/bin:/usr/sbin:/sbin:/root/bin:/usr/local/bin
declare -a valid_commands=(start finish)

# Change these variables to match your exercise
this='monitor-troubleshoot'
title='Guided Exercise: Troubleshooting Using the Cluster Monitoring Stack'

# Do not change these variables
target='workstation'
run_as_root='true'

source /etc/rht

function lab_start {

  ocp4_print_prereq_header

  ocp4_is_cluster_up
  ocp4_login_as_admin
  print_line
  ocp4_fail_if_project_exists "${this}"
  ocp4_exit_on_failure "It looks like you have already started this exercise. To try this exercise again, run 'lab ${this} finish' followed by 'lab ${this} start'."

  ocp4_print_setup_header

  print_line " Preparing the student's cluster:"
  ocp4_grab_lab_files "no-solution"

  if [ "$(oc get nodes -l env=dev -o name | grep worker03)" != "node/woker03" ]
  then
    pad2 "Adding the 'env' label to 'worker03'"
    if oc label node/worker03 env=dev
    then
      print_SUCCESS
    else
      print_FAIL
    fi
  fi
  pad2 "Creating a project for this exercise"
  if oc adm new-project ${this} --node-selector env=dev
  then
    print_SUCCESS
    pad2 "Deploying the 'hello' application"
    if oc create --save-config -f /home/student/${RHT_COURSE^^}/labs/${this}/hello.yml -n ${this}
    then
      print_SUCCESS
    else
      print_FAIL
    fi
    pad2 "Deploying the 'python-load' application"
    if oc create --save-config -f /home/student/${RHT_COURSE^^}/labs/${this}/python-load.yml -n ${this}
    then
      print_SUCCESS
    else
      print_FAIL
    fi
  else
    print_FAIL
  fi

  ocp4_print_setup_footer
}


function lab_finish {

  ocp4_print_cleanup_header

  ocp4_login_as_admin
  ocp4_delete_project "${this}"
  ocp4_cleanup_lab_files

  if [ $(oc get nodes -l env -o name | wc -l) -gt 0 ]
  then
    pad2 "Removing the 'env' node label"
    if oc label node -l env env-
    then
      print_SUCCESS
    else
      print_FAIL
    fi
  fi

  ocp4_print_cleanup_footer
}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
