#!/bin/bash
#
# Copyright 2020 Red Hat, Inc.
#
# NAME
#     lab-TEMPLATE - lab script for DO380-OCP4
#
# SYNOPSIS
#     lab-TEMPLATE {start|grade|finish}
#
#        start  - prepare the system for starting the lab
#        grade  - perform evaluation steps on the system
#        finish - perform post-lab finish
#
# DESCRIPTION
#     This script, based on singular argument, either does start or finish for
#     the [name of the exercise]
#
# CHANGELOG
#   * Tue May 19 Your Name <yname@redhat.com>
#   - original code

#########################################################################
#########################################################################
#                   How to use this template:
#
# 1. Rename the file to lab-<something_related_to_your_lab>
# 2. Adjust the comments above
# 3. Modify the two functions, lab_setup and lab_grade to perform the
#    steps you desire. All work is performed on workstation, so ssh and
#    scp must be used to perform grading steps on remote host to be graded
# 4. Remove these "How to use this template" comments
# 5. If you need to retrieve some values from the cluster, look at
#    http://sferich888.blogspot.com.br/2017/01/learning-using-jsonpath-with-openshift.html
#########################################################################
#########################################################################

PATH=/usr/bin:/bin:/usr/sbin:/sbin:/root/bin:/usr/local/bin
declare -a valid_commands=(start finish)

# Change these variables to match your exercise
this='automation-resources'
title='Guided Exercise: Querying OpenShift Resources'

# Do not change these variables
target='workstation'
run_as_root='true'


function lab_start {
  ocp4_print_prereq_header
  ocp4_is_cluster_up
  ocp4_exit_on_failure

  print_line
  print_line " Preparing the student's cluster:"
  ocp4_grab_lab_files
  ocp4_exit_on_failure

  ocp4_login_as_kubeadmin

  ocp4_restore_oauth
}

function lab_finish {
  ocp4_print_cleanup_header

  ocp4_login_as_kubeadmin

  ocp4_restore_oauth

  ocp4_cleanup_lab_files
  ocp4_print_cleanup_footer
}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
