#!/bin/bash
#
# Copyright 2020 Red Hat, Inc.
#
# NAME
#     lab-gitops-deploy - lab script for DO380-OCP4
#
# SYNOPSIS
#     lab-gitops-deploy {start|finish}
#
#        start  - prepare the system for starting the lab
#        finish - perform post-lab finish
#
# DESCRIPTION
#     This script, based on singular argument, either does start or finish for
#     "Deploying Jenkins on OpenShift"
#
# CHANGELOG
#   * Wed Jul 29 Michael Phillips <miphilli@redhat.com>
#   - added the ocp4_login_as_admin function after the ocp4_is_cluster_up function
#   * Tue Jun 19 Fernando Lozano <flozano@redhat.com>
#   - original code

#########################################################################

PATH=/usr/bin:/bin:/usr/sbin:/sbin:/root/bin:/usr/local/bin
declare -a valid_commands=(start finish)

# Change these variables to match your exercise
this='gitops-deploy'
title='Guided Exercise: Deploying Jenkins on OpenShift'

# Do not change these variables
target='workstation'
run_as_root='true'


function lab_start {

  ocp4_print_prereq_header

  ocp4_is_cluster_up
  ocp4_login_as_admin
  print_line
  ocp4_fail_if_project_exists "${this}"
  ocp4_exit_on_failure "It looks like you have already started this exercise. To try this exercise again, run 'lab ${this} finish' followed by 'lab ${this} start'."

  ocp4_print_setup_header

  print_line
  print_line " Preparing the student's cluster:"
  ocp4_restore_oauth
  ocp4_grab_lab_files 'no-solution'

  ocp4_print_setup_footer
}


function lab_finish {
  ocp4_print_cleanup_header
  ocp4_login_as_admin

  ocp4_restore_oauth

  local token='/home/student/developer-token.txt'
  if [ -r "${token}" ]
  then
    pad2 "Removing the Jenkins API token at '${token}'"
    if rm "${token}"
    then
      print_SUCCESS
    else
      print_FAIL
    fi
  fi

  local gitrepo="/home/student/${this}"
  if [ -d "${gitrepo}" ]
  then
    pad2 "Removing the Git repository clone at '${gitrepo}'"
    if rm -rf "${gitrepo}"
    then
      print_SUCCESS
    else
      print_FAIL
    fi
  fi

  ocp4_cleanup_lab_files 'no-solution'
  ocp4_print_cleanup_footer
}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
