#!/bin/bash
#
# Copyright 2020 Red Hat, Inc.
#
# NAME
#     lab-workers-degrade - lab script for DO380-OCP4
#
# SYNOPSIS
#     lab-workers-degarde {start|finish}
#
#        start  - prepare the system for starting the lab
#        finish - perform post-lab finish
#
# DESCRIPTION
#     This script, based on singular argument, either does start or finish for
#     the Profiling Degraded Worker Nodes
#
# CHANGELOG
#   * Tue Jul 21 Harpal Singh <harpasin@redhat.com>
#   - Adding project deletion
#   * Tue June 23 Harpal Singh <harpasin@redhat.com>
#   - initial creation


PATH=/usr/bin:/bin:/usr/sbin:/sbin:/root/bin:/usr/local/bin
declare -a valid_commands=(start finish)

# Change these variables to match your exercise
this='workers-degarde'
project='workers-degrade'
title='Guided Exercise: Profiling Degraded Worker Nodes'
playbook_dir="/usr/local/lib/ansible"

# Do not change these variables
target='workstation'
run_as_root='true'


function lab_start {

  ocp4_print_prereq_header

  ocp4_is_cluster_up
  print_line

  ocp4_print_setup_header

  #TODO: Incorporate into the SHLIB
  pad2 "Ensuring node configuration"
  playbook_args="${playbook_dir}/storage/check_workers.yml"
  if ansible-playbook ${playbook_args}
  then
    # The extra worker nodes are present; ensure correct labels.
    if oc label --overwrite node/worker0{4,5,6} node-role.kubernetes.io/infra= && \
      oc label node/worker0{4,5,6} node-role.kubernetes.io/worker-
    then
      print_SUCCESS
    else
      print_FAIL
    fi
  else
    #If the extra workers are not present, not necessary to ensure configuration.
    print_SUCCESS
  fi


  print_line
  print_line " Degrading worker node (Please wait for 2 Minutes to finish degrading)"

  ocp4_stop_crio_service

  ocp4_login_as_kubeadmin

  ocp4_print_setup_footer
}


function lab_finish {

  ocp4_print_cleanup_header

  ocp4_login_as_kubeadmin

  ocp4_start_crio_service

  ocp4_delete_project "${project}"

  ocp4_print_cleanup_footer
}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
