#!/bin/bash
#
# Copyright 2020 Red Hat, Inc.
#
# NAME
#     lab-operators-install - lab script for DO380-OCP4
#
# SYNOPSIS
#     lab-operators-install {start|finish}
#
#        start  - prepare the system for starting the lab
#        finish - perform post-lab finish
#
# DESCRIPTION
#     This script, based on singular argument, either does start or finish for
#     the Installing Operators GE
#
# CHANGELOG
#   * Tue Jun 16 Iván Chavero <ichavero@redhat.com>
#   - initial creation


PATH=/usr/bin:/bin:/usr/sbin:/sbin:/root/bin:/usr/local/bin
declare -a valid_commands=(start finish)

# Change these variables to match your exercise
this='operators-install'
title='Guided Exercise: Installing Operators'
playbook_dir="/usr/local/lib/ansible"

# Do not change these variables
target='workstation'
run_as_root='true'


function lab_start {

  ocp4_print_prereq_header

  ocp4_is_cluster_up
  print_line
  ocp4_fail_if_project_exists "openshift-metering"

  pad2 "Group openshift-metering absent"
  if oc get OperatorGroup "openshift-metering" -o name
  then
    print_FAIL
  else
    print_SUCCESS
  fi

  pad2 "Subscription ge-openshift-metering absent"
  if oc get sub "ge-openshift-metering" -o name
  then
    print_FAIL
  else
    print_SUCCESS
  fi

  ocp4_print_setup_header

  print_line
  print_line " Preparing the student's cluster:"

  ocp4_login_as_admin

  ocp4_print_setup_footer
}


function lab_finish {

  ocp4_print_cleanup_header

  ocp4_login_as_admin

  ocp4_delete_group "ge-openshift-metering"


  if oc get OperatorGroup "openshift-metering" -o name
  then
    pad2 "Remove openshift-metering OperatorGroup"
    if oc delete OperatorGroup "openshift-metering"; then
      print_SUCCESS
    else
      print_FAIL
    fi
  fi

  if oc get sub "ge-openshift-metering" -o name
  then
    pad2 "Remove ge-openshift-metering subscription"
    if oc delete sub "ge-openshift-metering"; then
      print_SUCCESS
    else
      print_FAIL
    fi
  fi

  ocp4_delete_project "openshift-metering"

  ocp4_print_cleanup_footer
}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/${platform_lib}

grading_main_program "$@"
